services:
  flash:
    build: .
    container_name: flash_app
    ports:
      - "7000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mon-autre-service.rule=Host(`flash.book-plouc.fr`)"  
      - "traefik.http.routers.mon-autre-service.entrypoints=websecure"  
      - "traefik.http.routers.mon-autre-service.tls=true"
      - "traefik.http.routers.mon-autre-service.tls.certresolver=lets-encrypt"
      - "traefik.http.services.mon-autre-service.loadbalancer.server.port=8000"  # Port interne du service
    volumes:
      - .:/app
    networks:
      - traefik

networks:
  traefik:
    external: true